runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: tetris/css
  
- url: /js
  static_dir: tetris/js
  
- url: /images
  static_dir: tetris/images
  
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
